GET http://localhost:8080/books

POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "El Quijote",
    "author": "Miguel de Cervantes"
}

GET http://localhost:8080/books/2

POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "Caperucita Roja",
    "author": "Uknown"
}


PUT http://localhost:8080/books/1
Content-Type: application/json

{
    "title": "El Quijote cambiado",
    "author": "Miguel de Cervantes"
}

DELETE http://localhost:8080/books/1

POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "Shingeki no Kyojin",
    "author": "Isayama"
}